<?php

/*
	(C)2012 ID-INFORMATIK. WebFrameWork(R)
	Fonctions utiles
*/

//erreurs strings
global $_req_err_str;
$_req_err_str = array_merge($_req_err_str,array(
	"cant_open_default_file"=>"Le fichier défaut ne peut pas être ouvert",
	"cant_addIndexNode"=>"Impossible d'ajouter ce noeud de valeur à l'index",
	"cant_save_default_file"=>"Impossible de sauvegarder le fichier défaut"
	));

?>
